apiVersion: apps/v1
kind: Deployment
metadata:
  name: actividad-16
  labels:
    app: actividad-16
spec:
  selector:
    matchLabels:
      app: actividad-16
  replicas: 2
  template:
    metadata:
      labels:
        app: actividad-16
    spec:
      containers:
        - name: actividad-16
          image: nginx
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: actividad-16-cm
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /etc/db
              name: secret-volume
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 21
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: actividad-16-secret
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 30%
---
apiVersion: v1
kind: Service
metadata:
  name: actividad-16-svc
spec:
  type: ClusterIP
  selector:
    app: actividad-16
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actividad-16-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: actividad-16-svc
                port:
                  number: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: actividad-16
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: actividad-16
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Secret
metadata:
  name: actividad-16-secret
data:
  db_host: aG9sYQ==
  db_password: bXVuZG8=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: actividad-16-cm
data:
  APP_ENV: prod
  APP_NAME: diplomado-grupo4-actividad-16
